In [14]:
import pandas as pd
import numpy as np
import os

os.chdir('/Users/antoniojurlina/Google Drive/Spring 2021/SIE 598/data/')

In [15]:
real=pd.read_csv('RDC_Inventory_Core_Metrics_State_History.csv')

In [13]:
real.tail()

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
2800,201607,iowa,ia,169950.0,NaN,NaN,14764,NaN,NaN,65.0,...,NaN,230796,NaN,NaN,18856,NaN,NaN,0.2772,NaN,NaN
2801,201607,south carolina,sc,239950.0,NaN,NaN,35380,NaN,NaN,87.0,...,NaN,365814,NaN,NaN,45398,NaN,NaN,0.2832,NaN,NaN
2802,201607,nebraska,ne,193050.0,NaN,NaN,5132,NaN,NaN,51.0,...,NaN,253851,NaN,NaN,8839,NaN,NaN,0.7223,NaN,NaN
2803,201607,virginia,va,285050.0,NaN,NaN,49354,NaN,NaN,73.0,...,NaN,401872,NaN,NaN,55276,NaN,NaN,0.1200,NaN,NaN
2804,201607,west virginia,wv,165050.0,NaN,NaN,10021,NaN,NaN,91.0,...,NaN,217323,NaN,NaN,11328,NaN,NaN,0.1304,NaN,NaN

In [4]:
real.shape

(2805, 39)

In [5]:
real.shape[0]/51

55.0

In [6]:
real.set_index('month_date_yyyymm', inplace=True)
real.head()

,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
month_date_yyyymm,,,,,,,,,,,,,,,,,,,,,
202101,delaware,de,358050.0,0.0258,0.1002,1582,-0.1558,-0.5609,91.0,0.1974,...,-0.0133,488354,0.0395,0.1432,4059,-0.1368,0.0305,1.5657,0.0567,1.4725
202101,idaho,id,465040.0,0.0816,0.2433,1817,-0.1881,-0.6908,66.0,0.1786,...,-0.0427,977816,0.1570,0.6033,5554,-0.1156,-0.1471,2.0567,0.2506,1.9486
202101,arizona,az,419050.0,0.0771,0.1403,8212,-0.1487,-0.5687,46.0,0.0000,...,-0.0405,758396,0.1329,0.2679,22191,-0.1257,-0.2780,1.7023,0.0710,1.0878
202101,north dakota,nd,235050.0,-0.0053,0.0444,1992,-0.1487,-0.2949,92.0,0.0514,...,-0.0105,281329,0.0055,0.0382,2732,-0.1319,-0.1658,0.3715,0.0266,0.2122
202101,maryland,md,349050.0,0.0205,0.0579,6885,-0.1406,-0.5358,59.0,0.0926,...,-0.0927,521490,0.0423,0.1250,17332,-0.1330,0.0193,1.5174,0.0219,1.3708

In [7]:
a1=real[(real.index == 202101) | (real.index == 202001)]

In [8]:
a1.shape

(102, 38)

In [9]:
a1.head()

,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
month_date_yyyymm,,,,,,,,,,,,,,,,,,,,,
202101,delaware,de,358050.0,0.0258,0.1002,1582,-0.1558,-0.5609,91.0,0.1974,...,-0.0133,488354,0.0395,0.1432,4059,-0.1368,0.0305,1.5657,0.0567,1.4725
202101,idaho,id,465040.0,0.0816,0.2433,1817,-0.1881,-0.6908,66.0,0.1786,...,-0.0427,977816,0.1570,0.6033,5554,-0.1156,-0.1471,2.0567,0.2506,1.9486
202101,arizona,az,419050.0,0.0771,0.1403,8212,-0.1487,-0.5687,46.0,0.0000,...,-0.0405,758396,0.1329,0.2679,22191,-0.1257,-0.2780,1.7023,0.0710,1.0878
202101,north dakota,nd,235050.0,-0.0053,0.0444,1992,-0.1487,-0.2949,92.0,0.0514,...,-0.0105,281329,0.0055,0.0382,2732,-0.1319,-0.1658,0.3715,0.0266,0.2122
202101,maryland,md,349050.0,0.0205,0.0579,6885,-0.1406,-0.5358,59.0,0.0926,...,-0.0927,521490,0.0423,0.1250,17332,-0.1330,0.0193,1.5174,0.0219,1.3708

In [10]:
state_set=set(a1.state)

In [ ]:
len(state_set)

In [ ]:
a21=a1.loc[[202101],['state','median_listing_price','active_listing_count','median_days_on_market']]
a21.head(10)

In [ ]:
a21.set_index("state", inplace=True)
a21.head(10)

In [ ]:
a3=a21.rename(columns={'median_listing_price': 'MLP', 'active_listing_count': "ALC",'median_days_on_market': 'MDOM'})

In [ ]:
a3.head(8)

In [ ]:
a20=a1.loc[[202001],['state','median_listing_price','active_listing_count','median_days_on_market']]
a20.head(10)

In [ ]:
a20.set_index("state", inplace=True)
a20.head(10)

In [ ]:
a4=a20.rename(columns={'median_listing_price': 'MLP', 'active_listing_count': "ALC",'median_days_on_market': 'MDOM'})

In [ ]:
a4.head(8)

In [ ]:
subtractionResults = a3 - a4 # Jan 2021 - Jan 2020

In [ ]:
subtractionResults

In [ ]:
a3.loc['delaware']

In [ ]:
a4.loc['delaware']

In [ ]:
a3.loc['delaware']-a4.loc['delaware']

In [ ]:
real.columns